#pragma once
#include "barricadefactory.h"
#include "objectfactory.h"
#include "playerfactory.h"
#include "shelffactory.h"
#include "useablefactory.h"
#include "enemyfactory.h"
#include "toiletpaperfactory.h"
#include "spawnpointfactory.h"